# Generated by Django 5.0.6 on 2024-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_total_price_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
